import axios from "axios";

const BASE_URL = "http://api.alquran.cloud/v1";

export const api = axios.create({
  baseURL: BASE_URL,
});

export const namaSurahIndonesia = {
  1: "Pembukaan",
  2: "Sapi Betina",
  3: "Keluarga Imran",
  4: "Wanita",
  5: "Hidangan",
  6: "Binatang Ternak",
  7: "Tempat yang Tinggi",
  8: "Rampasan Perang",
  9: "Pengampunan",
  10: "Yunus",
  11: "Hud",
  12: "Yusuf",
  13: "Guntur",
  14: "Ibrahim",
  15: "Al-Hijr",
  16: "Lebah",
  17: "Perjalanan Malam",
  18: "Gua",
  19: "Maryam",
  20: "Thaha",
  21: "Para Nabi",
  22: "Haji",
  23: "Orang Mukmin",
  24: "Cahaya",
  25: "Pembeda",
  26: "Penyair",
  27: "Semut",
  28: "Kisah-Kisah",
  29: "Laba-Laba",
  30: "Bangsa Romawi",
  31: "Luqman",
  32: "Sujud",
  33: "Golongan Yang Bersekutu",
  34: "Saba'",
  35: "Maha Pencipta",
  36: "Yasin",
  37: "Barisan-Barisan",
  38: "Shad",
  39: "Rombongan",
  40: "Maha Pengampun",
  41: "Yang Dijelaskan",
  42: "Musyawarah",
  43: "Perhiasan",
  44: "Kabut",
  45: "Berlutut",
  46: "Bukit pasir",
  47: "Muhammad",
  48: "Kemenangan",
  49: "Kamar-Kamar",
  50: "Qaf",
  51: "Angin Yang Menerbangkan",
  52: "Bukit Tursina",
  53: "Bintang",
  54: "Bulan",
  55: "Maha Pengasih",
  56: "Hari Kiamat",
  57: "Besi",
  58: "Perempuan Penggugat",
  59: "Pengusiran",
  60: "Wanita Yang Dipuji",
  61: "Barisan",
  62: "jumat",
  63: "Orang-Orangf Munafik",
  64: "Pengungkapan Kesalahan",
  65: "Talak",
  66: "Pengharaman",
  67: "Kerajaan",
  68: "Pena",
  69: "Hari Kiamat",
  70: "Tempat Naik",
  71: "Nuh",
  72: "Jin",
  73: "Orang Yang Berselimut",
  74: "Orang Yang Berkemul",
  75: "Hari Kiamat",
  76: "Manusia",
  77: "Malaikat Yang Diutus",
  78: "Berita Besar",
  79: "Malaikat Yang Mencabut",
  80: "Bermuka Masah",
  81: "Penggulungan",
  82: "Terbelah",
  83: "Orang-Orang Yang Curang",
  84: "Terbelah",
  85: "Gugusan Bintang",
  86: "Yang Datang Di Malam Hari",
  87: "Maha Tinggi",
  88: "Hari Kiamat",
  89: "Fajar",
  90: "Negeri",
  91: "Matahari",
  92: "Malam",
  93: "Dhuha",
  94: "Lapang",
  95: "Buah Tin",
  96: "Segumpal Darah",
  97: "Kemuliaan",
  98: "Bukti Nyata",
  99: "Guncangan",
  100: "Kuda Yang Berlari Kencang",
  101: "Hari Kiamat",
  102: "Bermegah-Megahan",
  103: "Asar",
  104: "Pengumpat",
  105: "Gajah",
  106: "Quraisy",
  107: "Barang Yang Berguna",
  108: "Pemberi Yang Banyak",
  109: "Orang-Orang Kafir",
  110: "Pertolongan",
  111: "Api Yang Bergejolak",
  112: "Ikhlas",
  113: "Subuh",
  114: "Manusia",
};
